name: Autograding Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deve adicionar circulos
        id: adicionar-circulos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-circulos
          command: gradle test --tests 'CircleTests.adicionarCirculos'
          timeout: 10
          max-score: 5

      - name: Não deve adicionar circulo limite invalido
        id: adicionar-circulo-limite-invalido
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-circulo-limite-invalido
          command: gradle test --tests 'CircleTests.adicionarCirculoLimiteInvalido'
          timeout: 10
          max-score: 5

      - name: Não deve adicionar circulo duplicado
        id: adicionar-circulo-duplicado
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-circulo-duplicado
          command: gradle test --tests 'CircleTests.adicionarCirculoDuplicado'
          timeout: 10
          max-score: 5

      - name: Deve achar circulo existente
        id: buscando-circulo-existente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: buscando-circulo-existente
          command: gradle test --tests 'CircleTests.buscandoCirculoExistente'
          timeout: 10
          max-score: 5

      - name: Não deve achar circulo inexistente
        id: buscando-circulo-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: buscando-circulo-inexistente
          command: gradle test --tests 'CircleTests.buscandoCirculoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve recuperando todos os circulos
        id: recuperando-todos-os-circulos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: recuperando-todos-os-circulos
          command: gradle test --tests 'CircleTests.recuperandoTodosOsCirculos'
          timeout: 10
          max-score: 5

      - name: Deve remover circulo existente
        id: removendo-circulo-existente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-circulo-existente
          command: gradle test --tests 'CircleTests.removendoCirculoExistente'
          timeout: 10
          max-score: 5

      - name: Não deve remover circulo inexistente
        id: removendo-circulo-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-circulo-inexistente
          command: gradle test --tests 'CircleTests.removendoCirculoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve atualizar circulo existente
        id: atualizando-circulo-existente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: atualizando-circulo-existente
          command: gradle test --tests 'CircleTests.atualizandoCirculoExistente'
          timeout: 10
          max-score: 5

      - name: Não deve atualizar circulo com limite invalido
        id: atualizando-circulo-limite-invalido
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: atualizando-circulo-limite-invalido
          command: gradle test --tests 'CircleTests.atualizandoCirculoLimiteInvalido'
          timeout: 10
          max-score: 5

      - name: Não deve atualizar circulo inexistente
        id: atualizando-circulo-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: atualizando-circulo-inexistente
          command: gradle test --tests 'CircleTests.atualizandoCirculoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve adicionar contato
        id: adicionar-contato
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato
          command: gradle test --tests 'ContactTests.adicionarContato'
          timeout: 10
          max-score: 5

      - name: Não deve adicionar contato duplicado
        id: adicionar-contato-duplicado
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato-duplicado
          command: gradle test --tests 'ContactTests.adicionarContatoDuplicado'
          timeout: 10
          max-score: 5

      - name: Deve remover contato existente
        id: removendo-contato
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-contato
          command: gradle test --tests 'ContactTests.removendoContato'
          timeout: 10
          max-score: 5

      - name: Não deve remover contato inexistente
        id: removendo-contato-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-contato-inexistente
          command: gradle test --tests 'ContactTests.removendoContatoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve recuperar contato existente
        id: recuperando-contato
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: recuperando-contato
          command: gradle test --tests 'ContactTests.recuperandoContato'
          timeout: 10
          max-score: 5

      - name: Não deve recuperar contato inexistene
        id: recuperando-contato-inexistene
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: recuperando-contato-inexistene
          command: gradle test --tests 'ContactTests.recuperandoContatoInexistene'
          timeout: 10
          max-score: 5

      - name: Deve recuperar todos os contatos
        id: recuperando-todos-os-contatos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: recuperando-todos-os-contatos
          command: gradle test --tests 'ContactTests.recuperandoTodosOsContatos'
          timeout: 10
          max-score: 5

      - name: Deve atualizar contato
        id: atualizando-contato
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: atualizando-contato
          command: gradle test --tests 'ContactTests.atualizandoContato'
          timeout: 10
          max-score: 5

      - name: Não deve atualizar contato inexistente
        id: atualizando-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: atualizando-inexistente
          command: gradle test --tests 'ContactTests.atualizandoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve favoritar um contato
        id: favoritando-um-contato
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: favoritando-um-contato
          command: gradle test --tests 'ContactTests.favoritandoUmContato'
          timeout: 10
          max-score: 5

      - name: Não deve favoritar um contato inexistente
        id: favoritando-um-contato-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: favoritando-um-contato-inexistente
          command: gradle test --tests 'ContactTests.favoritandoUmContatoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve desfavoritar um contato
        id: desfavoritando-um-contato
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: desfavoritando-um-contato
          command: gradle test --tests 'ContactTests.desfavoritandoUmContato'
          timeout: 10
          max-score: 5

      - name: Não deve desfavoritar um contato inexistente
        id: desfavoritando-um-contato-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: desfavoritando-um-contato-inexistente
          command: gradle test --tests 'ContactTests.desfavoritandoUmContatoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve recuperar todos os favoritos
        id: recuperando-todos-os-favoritos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: recuperando-todos-os-favoritos
          command: gradle test --tests 'ContactTests.recuperandoTodosOsFavoritos'
          timeout: 10
          max-score: 5

      - name: Deve adicionar contato a um circulo existente
        id: adicionar-contato-circulo-existente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato-circulo-existente
          command: gradle test --tests 'ContactsCircleRelationsTest.adicionarContatoCirculoExistente'
          timeout: 10
          max-score: 5

      - name: Não deve adicionar contato inexistente a um circulo existente
        id: adicionar-contato-inexistente-circulo-existente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato-inexistente-circulo-existente
          command: gradle test --tests 'ContactsCircleRelationsTest.adicionarContatoInexistenteCirculoExistente'
          timeout: 10
          max-score: 5

      - name: Não deve adicionar contato a um circulo inexistente
        id: adicionar-contato-circulo-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato-circulo-inexistente
          command: gradle test --tests 'ContactsCircleRelationsTest.adicionarContatoCirculoInexistente'
          timeout: 10
          max-score: 5

      - name: Não deve adicionar contato duplicado a um circulo
        id: adicionar-contato-duplicado-circulo-existente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato-duplicado-circulo-existente
          command: gradle test --tests 'ContactsCircleRelationsTest.adicionarContatoDuplicadoCirculoExistente'
          timeout: 10
          max-score: 5

      - name: Não deve ultrapassar o limite
        id: adicionar-alem-do-limite
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-alem-do-limite
          command: gradle test --tests 'ContactsCircleRelationsTest.adicionarAlemDoLimite'
          timeout: 10
          max-score: 5

      - name: Deve ser possível adicionar contato a vários circulos
        id: adicionar-contato-varios-circulos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: adicionar-contato-varios-circulos
          command: gradle test --tests 'ContactsCircleRelationsTest.adicionarContatoVariosCirculos'
          timeout: 10
          max-score: 5

      - name: Deve remover o contato de um circulo
        id: removendo-contato-do-circulo
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-contato-do-circulo
          command: gradle test --tests 'ContactsCircleRelationsTest.removendoContatoDoCirculo'
          timeout: 10
          max-score: 5

      - name: Não deve remover contato inexistente de um circulo
        id: removendo-contato-inexistente-do-circulo
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-contato-inexistente-do-circulo
          command: gradle test --tests 'ContactsCircleRelationsTest.removendoContatoInexistenteDoCirculo'
          timeout: 10
          max-score: 5

      - name: Não deve remover o contato de um circulo inexistente
        id: removendo-contato-do-circulo-inexistente
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-contato-do-circulo-inexistente
          command: gradle test --tests 'ContactsCircleRelationsTest.removendoContatoDoCirculoInexistente'
          timeout: 10
          max-score: 5

      - name: Deve ser possivel remover um circulo com contatos
        id: removendo-circulo-que-possui-contatos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-circulo-que-possui-contatos
          command: gradle test --tests 'ContactsCircleRelationsTest.removendoCirculoQuePossuiContatos'
          timeout: 10
          max-score: 5

      - name: Deve remover contato dos circulos
        id: removendo-contatos-que-esta-em-circulos
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: removendo-contatos-que-esta-em-circulos
          command: gradle test --tests 'ContactsCircleRelationsTest.removendoContatosQueEstaEmCirculos'
          timeout: 10
          max-score: 5

      - name: Deve encontrar circulos em comum
        id: circulos-em-comum
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: circulos-em-comum
          command: gradle test --tests 'ContactsCircleRelationsTest.circulosEmComum'
          timeout: 10
          max-score: 5


      # Relatório final
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          ADICIONAR-CIRCULOS_RESULTS: "${{steps.adicionar-circulos.outputs.result}}"
          ADICIONAR-CIRCULO-LIMITE-INVALIDO_RESULTS: "${{steps.adicionar-circulo-limite-invalido.outputs.result}}"
          ADICIONAR-CIRCULO-DUPLICADO_RESULTS: "${{steps.adicionar-circulo-duplicado.outputs.result}}"
          BUSCANDO-CIRCULO-EXISTENTE_RESULTS: "${{steps.buscando-circulo-existente.outputs.result}}"
          BUSCANDO-CIRCULO-INEXISTENTE_RESULTS: "${{steps.buscando-circulo-inexistente.outputs.result}}"
          RECUPERANDO-TODOS-OS-CIRCULOS_RESULTS: "${{steps.recuperando-todos-os-circulos.outputs.result}}"
          REMOVENDO-CIRCULO-EXISTENTE_RESULTS: "${{steps.removendo-circulo-existente.outputs.result}}"
          REMOVENDO-CIRCULO-INEXISTENTE_RESULTS: "${{steps.removendo-circulo-inexistente.outputs.result}}"
          ATUALIZANDO-CIRCULO-EXISTENTE_RESULTS: "${{steps.atualizando-circulo-existente.outputs.result}}"
          ATUALIZANDO-CIRCULO-LIMITE-INVALIDO_RESULTS: "${{steps.atualizando-circulo-limite-invalido.outputs.result}}"
          ATUALIZANDO-CIRCULO-INEXISTENTE_RESULTS: "${{steps.atualizando-circulo-inexistente.outputs.result}}"
          ADICIONAR-CONTATO_RESULTS: "${{steps.adicionar-contato.outputs.result}}"
          ADICIONAR-CONTATO-DUPLICADO_RESULTS: "${{steps.adicionar-contato-duplicado.outputs.result}}"
          REMOVENDO-CONTATO_RESULTS: "${{steps.removendo-contato.outputs.result}}"
          REMOVENDO-CONTATO-INEXISTENTE_RESULTS: "${{steps.removendo-contato-inexistente.outputs.result}}"
          RECUPERANDO-CONTATO_RESULTS: "${{steps.recuperando-contato.outputs.result}}"
          RECUPERANDO-CONTATO-INEXISTENE_RESULTS: "${{steps.recuperando-contato-inexistene.outputs.result}}"
          RECUPERANDO-TODOS-OS-CONTATOS_RESULTS: "${{steps.recuperando-todos-os-contatos.outputs.result}}"
          ATUALIZANDO-CONTATO_RESULTS: "${{steps.atualizando-contato.outputs.result}}"
          ATUALIZANDO-INEXISTENTE_RESULTS: "${{steps.atualizando-inexistente.outputs.result}}"
          FAVORITANDO-UM-CONTATO_RESULTS: "${{steps.favoritando-um-contato.outputs.result}}"
          FAVORITANDO-UM-CONTATO-INEXISTENTE_RESULTS: "${{steps.favoritando-um-contato-inexistente.outputs.result}}"
          DESFAVORITANDO-UM-CONTATO_RESULTS: "${{steps.desfavoritando-um-contato.outputs.result}}"
          DESFAVORITANDO-UM-CONTATO-INEXISTENTE_RESULTS: "${{steps.desfavoritando-um-contato-inexistente.outputs.result}}"
          RECUPERANDO-TODOS-OS-FAVORITOS_RESULTS: "${{steps.recuperando-todos-os-favoritos.outputs.result}}"
          ADICIONAR-CONTATO-CIRCULO-EXISTENTE_RESULTS: "${{steps.adicionar-contato-circulo-existente.outputs.result}}"
          ADICIONAR-CONTATO-INEXISTENTE-CIRCULO-EXISTENTE_RESULTS: "${{steps.adicionar-contato-inexistente-circulo-existente.outputs.result}}"
          ADICIONAR-CONTATO-CIRCULO-INEXISTENTE_RESULTS: "${{steps.adicionar-contato-circulo-inexistente.outputs.result}}"
          ADICIONAR-CONTATO-DUPLICADO-CIRCULO-EXISTENTE_RESULTS: "${{steps.adicionar-contato-duplicado-circulo-existente.outputs.result}}"
          ADICIONAR-ALEM-DO-LIMITE_RESULTS: "${{steps.adicionar-alem-do-limite.outputs.result}}"
          ADICIONAR-CONTATO-VARIOS-CIRCULOS_RESULTS: "${{steps.adicionar-contato-varios-circulos.outputs.result}}"
          REMOVENDO-CONTATO-DO-CIRCULO_RESULTS: "${{steps.removendo-contato-do-circulo.outputs.result}}"
          REMOVENDO-CONTATO-INEXISTENTE-DO-CIRCULO_RESULTS: "${{steps.removendo-contato-inexistente-do-circulo.outputs.result}}"
          REMOVENDO-CONTATO-DO-CIRCULO-INEXISTENTE_RESULTS: "${{steps.removendo-contato-do-circulo-inexistente.outputs.result}}"
          REMOVENDO-CIRCULO-QUE-POSSUI-CONTATOS_RESULTS: "${{steps.removendo-circulo-que-possui-contatos.outputs.result}}"
          REMOVENDO-CONTATOS-QUE-ESTA-EM-CIRCULOS_RESULTS: "${{steps.removendo-contatos-que-esta-em-circulos.outputs.result}}"
          CIRCULOS-EM-COMUM_RESULTS: "${{steps.circulos-em-comum.outputs.result}}"
        with:
          runners: adicionar-circulos,adicionar-circulo-limite-invalido,adicionar-circulo-duplicado,buscando-circulo-existente,buscando-circulo-inexistente,recuperando-todos-os-circulos,removendo-circulo-existente,removendo-circulo-inexistente,atualizando-circulo-existente,atualizando-circulo-limite-invalido,atualizando-circulo-inexistente,adicionar-contato,adicionar-contato-duplicado,removendo-contato,removendo-contato-inexistente,recuperando-contato,recuperando-contato-inexistene,recuperando-todos-os-contatos,atualizando-contato,atualizando-inexistente,favoritando-um-contato,favoritando-um-contato-inexistente,desfavoritando-um-contato,desfavoritando-um-contato-inexistente,recuperando-todos-os-favoritos,adicionar-contato-circulo-existente,adicionar-contato-inexistente-circulo-existente,adicionar-contato-circulo-inexistente,adicionar-contato-duplicado-circulo-existente,adicionar-alem-do-limite,adicionar-contato-varios-circulos,removendo-contato-do-circulo,removendo-contato-inexistente-do-circulo,removendo-contato-do-circulo-inexistente,removendo-circulo-que-possui-contatos,removendo-contatos-que-esta-em-circulos,circulos-em-comum
